version: '3'

services:
    db:
      image: mysql:5.7
      environment:
        MYSQL_DATABASE: 'db'
        MYSQL_USER: 'root'
        MYSQL_PASSWORD: 'password'
        MYSQL_ROOT_PASSWORD: 'password'
      ports:
        - '5000:5000'
      volumes:
        - my-db:/var/lib/mysql

    web:
      build: .
      command: python manage.py runserver 0.0.0.0:8000
      volumes:
        - .:/code
      ports:
        - "8000:8000"
      depends_on:
        - db

    phpmyadmin:
      depends_on:
        - db
      image: phpmyadmin/phpmyadmin
      ports:
        - '8070:80'
      environment:
        PMA_HOST: db
        MYSQL_USER: root
        MYSQL_ROOT_PASSWORD: password

volumes:
  my-db:
