# Generated by Django 2.0.13 on 2019-10-07 05:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('changeconfig', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changeconfig',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='changeconfig',
            name='hotel_code',
        ),
        migrations.RemoveField(
            model_name='changeconfig',
            name='hotel_id',
        ),
        migrations.RemoveField(
            model_name='changeconfig',
            name='site_fqdn',
        ),
    ]
