# Generated by Django 2.0.13 on 2019-10-07 05:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changeconfig', '0002_auto_20191007_0520'),
    ]

    operations = [
        migrations.AddField(
            model_name='changeconfig',
            name='site_fqdn',
            field=models.CharField(default='', max_length=50),
        ),
    ]
