# Generated by Django 2.0.13 on 2019-10-05 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ChangeConfig',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=30)),
                ('password', models.CharField(max_length=50)),
                ('hotel_id', models.CharField(max_length=2)),
                ('hotel_code', models.CharField(default='', max_length=10)),
                ('currency', models.CharField(default='', max_length=6)),
                ('site_fqdn', models.CharField(default='', max_length=50)),
            ],
        ),
    ]
