# Generated by Django 2.0.13 on 2019-09-07 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('changeconfig', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='changeconfig',
            name='fqdn',
        ),
        migrations.AddField(
            model_name='changeconfig',
            name='GiveFqdn',
            field=models.CharField(default='0000000', max_length=20),
        ),
    ]
